sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --include molo.yourwords ^yourwords/
  - mkdir -p testapp/testapp/templates/core/tags/
  - cp test_settings.py testapp/testapp/settings/local.py
  - cp molo/yourwords/test_templates/section_page.html testapp/testapp/templates/core/section_page.html
  - cp molo/yourwords/test_templates/section_listing_homepage.html testapp/testapp/templates/core/tags/section_listing_homepage.html
  - flake8 testapp
  - testapp/./manage.py compress --settings=testapp.settings.production --force
  - pip install -e testapp
  - py.test --cov=molo
after_success:
  - coveralls
before_deploy:
  - pip install twine
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: I36TK0n33yR9PpQGX1bBgummw8uG+xlFXmhOF2xbDXv5/6lXR2AzGXOQJq3g4r+8VOuZLTrpG/YAXiU/nuk0wok4cqGtuW9+4BWu57bewaPweAMK7ebJ1o8znOsORqA4D1IBzIWujEh1PQ6yomqESNtk7MrutMFzJy/41tIJdvSH58tzaod0qv/odWfr4ocOUfD2cezVcARlzJ0S1YEcdfaFRxoq+0PEmNGwdUqZgBpf4IXP+dqO2gqm0SobD8/8ILxvMETbMRhDRmPX7zLwK9SMNP82XKGGXcjzFG9ySQK/g7BEWwv71F1Gy22jrlEIeCJHpC4a76Zue0ZJYY+vgZCNXwf18C/3HAcAIuA71EjJvX7XZzBUk8SCcwXafPEPEKgmoXtGEsFPrc+kHlk+Nna9HpiBWnePizG5EkZ1+6PMlrBF8KT5QjpEz/Z3JiY3Gmlfy9ahwN6lZW2PddTjRNDt5+82a0l4tvC8IKMX57AgBAMq7Lczop+N12uGO7AFEMaQsBL9zxH8b9ZA0gyreSoQTxvZwlguKp/iHmoNiqEwYKNiIYUyszYB9uVsoL8YVZy0IQxPOyABonuUbl4zlCnBQrnONks3WCo2ISEghJSuPlVMEFUtwKH5iT+TAg2QZIKZjKG/cAQ0D16aAyQEj7fYiKiHNm2oXms3psLynWU=
  on:
    tags: true
    python: 3.6
